# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    
    services:    
      postgres:
        image: postgres:17.0-alpine3.20
        
        env:
          POSTGRES_USER : root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB : banking_systems
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
    
    - name: Install Golang Migrate
      run: $ curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$os-$arch.tar.gz | tar xvz

    - name: Run migration
      run: make migrateup 

    - name: Test
      run: make test
